#TO CHECK THE ERROR TYPE
NO_INPUT = 0
WRONG_INPUT = 1
NEGATIVE_VALUE = 3
IMPOSSIBLE_FILE = 4

#FILE FLAGS
FILE_EMPTY = 0
FILE_NOT_EMPTY = 1


#TO CHECK THE INPUT EXPECTED
EXPECT_INT = 0
EXPECT_FLOAT = 1
EXPECT_TUPLE = 2
EXPECT_STR = 3

#TO CHECK THE KEY NAME (you can add new keys if wanted)
KEY_NAME = ["WIDTH", "HEIGHT", "ENTRY", "EXIT",
            "OUTPUT_FILE", "PERFECT", "SEED"]

PERFECT_VALUES = ["1", "0", "TRUE", "FALSE"]
